version: "3"
services:
  devme:
    build: .
    restart: always
    ports:
      - "8000:8000"
    image: devme
    networks:
      - devme
    container_name: devme
    environment:
      - LOGURU_LEVEL=INFO
    volumes:
      - ./config.yaml:/devme/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  devme:
    name: devme
